# Generated by Django 5.2.4 on 2025-08-02 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dds_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflowstatement",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Сумма"
            ),
        ),
        migrations.AlterField(
            model_name="cashflowstatement",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="dds_app.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="cashflowstatement",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="cashflowstatement",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, verbose_name="Реальная дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="cashflowstatement",
            name="custom_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Пользовательское время создания"
            ),
        ),
        migrations.AlterField(
            model_name="cashflowstatement",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="dds_app.status",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="cashflowstatement",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="dds_app.subcategory",
                verbose_name="Подкатегория",
            ),
        ),
        migrations.AlterField(
            model_name="cashflowstatement",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="dds_app.type",
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="cashflowstatement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="dds_app.type",
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="dds_app.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="type",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="types",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
